/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obat;
import com.mysql.cj.x.protobuf.MysqlxPrepare;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fastabee
 */
public class obat extends javax.swing.JFrame {

    /**
     * Creates new form obat
     */
    public obat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        obat_table = new rojerusan.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        formsupplier = new javax.swing.JTextField();
        formnama = new javax.swing.JTextField();
        formkode = new javax.swing.JTextField();
        formstock = new javax.swing.JTextField();
        formharga = new javax.swing.JTextField();
        btnhapus = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        btnsearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        obat_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        obat_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        obat_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                obat_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(obat_table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 720, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<- Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Kozuka Gothic Pr6N M", 1, 18)); // NOI18N
        jLabel1.setText("DATA OBAT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 110, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\bgtek\\logo kecil.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 120, 60));

        jLabel3.setText("Supplier");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel5.setText("Kode Obat");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel6.setText("Stock Obat");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setText("Harga Obat");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        formsupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formsupplierActionPerformed(evt);
            }
        });
        jPanel1.add(formsupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 270, -1));
        jPanel1.add(formnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 270, -1));
        jPanel1.add(formkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 270, -1));

        formstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formstockActionPerformed(evt);
            }
        });
        jPanel1.add(formstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, -1));

        formharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formhargaActionPerformed(evt);
            }
        });
        jPanel1.add(formharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 270, -1));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 170, 70, -1));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 80, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 80, -1));

        btnsearch.setText("Seartch");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        btnsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnsearchKeyReleased(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formsupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formsupplierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formsupplierActionPerformed

    private void formstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formstockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formstockActionPerformed

    private void formhargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formhargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formhargaActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int id = Integer.parseInt(obat_table.getValueAt(obat_table.getSelectedRow(),0).toString());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    Statement st = con.createStatement();
    int r = JOptionPane.showConfirmDialog(this, "yakin hapus?");
    if(r==0){
    if(!st.execute("delete from obat where id="+id)){
        formWindowOpened(null);
    }else{
    JOptionPane.showMessageDialog(this, "batal hapus");
    }
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat","root", "");
            Statement s = con.createStatement();
            boolean b = s.execute("insert into obat(nama, kode, stok, harga, supplier) value ('"+formnama.getText()+"','"+formkode.getText()+"','"+formstock.getText()+"','"+formharga.getText()+"','"+formsupplier.getText()+"')");
        if(!b){
            JOptionPane.showMessageDialog(null, "berhasil tambah obat");
            formWindowOpened(null);
        }else{
        JOptionPane.showMessageDialog(null, "Gaagal");
        }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
       try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from obat");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        for (int i = 0; i < col; i++) {
            rowData[r][i] = set.getString(i + 1);
        }
        r++;
    }

    String[] ColumnName = {"NoId","nama", "kode", "stok", "harga", "supplier"};
    DefaultTableModel model = (DefaultTableModel) obat_table.getModel();
    model.setDataVector(rowData, ColumnName);

} catch (Exception e) {
    e.printStackTrace();
}

    }//GEN-LAST:event_formWindowOpened

    private void obat_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_obat_tableMouseClicked
        
        int id = Integer.parseInt(obat_table.getValueAt(obat_table.getSelectedRow(),0).toString());
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    Statement st = con.createStatement();
    ResultSet res  = st.executeQuery("select * from  obat where id="+id);
    while(res.next()){
    formnama.setText(res.getString("nama"));
    formharga.setText(res.getString("harga"));
    formstock.setText(res.getString("stok"));
    formsupplier.setText(res.getString("supplier"));
    formkode.setText(res.getString("kode"));
    
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_obat_tableMouseClicked

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
         int id = Integer.parseInt(obat_table.getValueAt(obat_table.getSelectedRow(),0).toString());
        try {
             Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    Statement st = con.createStatement();
   boolean b= st.execute("update obat set nama='"+formnama.getText()+"', stok='"+formstock.getText()+"', harga='"+formharga.getText()+"', kode='"+formkode.getText()+"', supplier='"+formsupplier.getText()+"' where id="+id);
        if(!b){
            formWindowOpened(null);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_btneditActionPerformed

    private void btnsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsearchKeyReleased
          try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from obat where nama like '%"+btnsearch.getText()+"%' ");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        for (int i = 0; i < col; i++) {
            rowData[r][i] = set.getString(i + 1);
        }
        r++;
    }

    String[] ColumnName = {"NoID","nama", "kode", "stok", "harga", "supplier"};
    DefaultTableModel model = (DefaultTableModel) obat_table.getModel();
    model.setDataVector(rowData, ColumnName);

} catch (Exception e) {
    e.printStackTrace();
}
        
        
    }//GEN-LAST:event_btnsearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new obat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JTextField btnsearch;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JTextField formharga;
    private javax.swing.JTextField formkode;
    private javax.swing.JTextField formnama;
    private javax.swing.JTextField formstock;
    private javax.swing.JTextField formsupplier;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSTableMetro obat_table;
    // End of variables declaration//GEN-END:variables
}
