/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package obat;

import com.mysql.cj.protocol.MessageHeader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttribute;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSTableMetro;

/**
 *
 * @author fastabee
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        customer = new javax.swing.JTextField();
        no_transaksi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        form_tanggal = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kode_barang = new javax.swing.JTextField();
        nama_barang = new javax.swing.JTextField();
        harga_barang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transakasi_table = new rojerusan.RSTableMetro();
        button1 = new java.awt.Button();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        totalbayar = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        tambahbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\bgtek\\logo kecil.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("TRANSAKSI OBAT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jButton1.setText("<-Kembali");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Nama Customer");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("No Transaksi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel1.add(customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 270, -1));

        no_transaksi.setEditable(false);
        no_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                no_transaksiMouseClicked(evt);
            }
        });
        no_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_transaksiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                no_transaksiKeyTyped(evt);
            }
        });
        jPanel1.add(no_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 270, -1));

        jLabel5.setText("Tanggal");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        form_tanggal.setEditable(false);
        form_tanggal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                form_tanggalMouseClicked(evt);
            }
        });
        form_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                form_tanggalActionPerformed(evt);
            }
        });
        jPanel1.add(form_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 120, -1));
        jPanel1.add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 70, -1));

        kode_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kode_barangKeyReleased(evt);
            }
        });
        jPanel1.add(kode_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 70, -1));
        jPanel1.add(nama_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, -1));
        jPanel1.add(harga_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 70, -1));

        jLabel6.setText("Jumlah");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel7.setText("Kode Barang");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabel8.setText("Nama Barang");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        jLabel9.setText("Harga");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        transakasi_table.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        transakasi_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        transakasi_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transakasi_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(transakasi_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 650, 130));

        button1.setLabel("Simpan");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel10.setText("Bayar");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 40, -1));

        jLabel11.setText("Total");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 40, -1));

        jLabel12.setText("Kembalian");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, 130, -1));
        jPanel1.add(totalbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 130, -1));

        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bayarKeyReleased(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 130, -1));

        tambahbtn.setText("Tambah");
        tambahbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahbtnActionPerformed(evt);
            }
        });
        jPanel1.add(tambahbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, -1));

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });
        jPanel1.add(hapusbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void form_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_form_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_form_tanggalActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        
        
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datenow = sdf.format(new Date());
        form_tanggal.setText(datenow);
        
                 try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from transaksi where no_transaksi like '%"+no_transaksi.getText()+"%' ");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        for (int i = 0; i < col; i++) {
            rowData[r][i] = set.getString(i + 1);
        }
        r++;
    }

    String[] ColumnName = {"NO" ,"No Transaksi", "Kode", "Nama", "Jumlah", "Harga", "Total"};
    DefaultTableModel model = (DefaultTableModel)transakasi_table.getModel();
    model.setDataVector(rowData, ColumnName);
    
     ResultSet totalSet = st.executeQuery("SELECT SUM(total) AS total_bayar FROM transaksi WHERE no_transaksi = '" + no_transaksi.getText() + "'");
        if (totalSet.next()) {
            int totalBayar = totalSet.getInt("total_bayar"); // Mengambil hasil SUM
            totalbayar.setText(String.valueOf(totalBayar)); // Menampilkan ke form
        } else {
            totalbayar.setText("0"); // Jika tidak ada data
        }
    

} catch (Exception e) {
    e.printStackTrace();
}
        
       
        
       
       
    
   
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void kode_barangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kode_barangKeyReleased
       try {
        // Load driver MySQL
        Class.forName("com.mysql.cj.jdbc.Driver");
        
        // Buat koneksi ke database
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
        
        // Buat query dengan PreparedStatement untuk mencegah SQL Injection
        String query = "SELECT * FROM obat WHERE kode LIKE ?";
        var pst = con.prepareStatement(query);
        pst.setString(1, "%" + kode_barang.getText() + "%");
        
        // Eksekusi query
        ResultSet set = pst.executeQuery();
        
        // Periksa apakah ada data dalam ResultSet
        if (set.next()) { // Pindah ke baris pertama jika ada data
            // Ambil data dari kolom dan tampilkan ke form
            nama_barang.setText(set.getString("nama"));
            harga_barang.setText(set.getString("harga"));
        } else {
            // Kosongkan form jika tidak ada data
            nama_barang.setText("");
            harga_barang.setText("");
        }
        
        // Tutup koneksi
        set.close();
        pst.close();
        con.close();
    } catch (Exception e) {
        e.printStackTrace();
    }
        
    }//GEN-LAST:event_kode_barangKeyReleased

    private void tambahbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahbtnActionPerformed
     int harga = Integer.parseInt(harga_barang.getText());
     int jumlahnya = Integer.parseInt(this.jumlah.getText());
     int total = harga * jumlahnya;
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat","root", "");
            Statement s = con.createStatement();
            boolean b = s.execute("insert into transaksi (no_transaksi, kode, nama, jumlah, harga, total, tanggal) value ('"+no_transaksi.getText()+"','"+kode_barang.getText()+"','"+nama_barang.getText()+"','"+jumlah.getText()+"','"+harga_barang.getText()+"','"+total+"','"+form_tanggal.getText()+"')");
            String updateStokQuery = "UPDATE obat SET stok = stok - " + jumlahnya + " WHERE kode = '" + kode_barang.getText() + "'";
        int rowsAffected = s.executeUpdate(updateStokQuery);
        if(!b && rowsAffected>0){
            JOptionPane.showMessageDialog(null, "berhasil tambah transaksi");
            formWindowOpened(null);
        }else{
        JOptionPane.showMessageDialog(null, "Gaagal");
        }
        
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
        
    }//GEN-LAST:event_tambahbtnActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void form_tanggalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_form_tanggalMouseClicked

            


        // TODO add your handling code here:
    }//GEN-LAST:event_form_tanggalMouseClicked

    private void no_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_no_transaksiMouseClicked
       
         Random random = new Random();
        int nomorAcak = 100000 + random.nextInt(900000); // Angka acak 6 digit
        no_transaksi.setText("TRX" + nomorAcak); // Contoh format nomor transaksi
        
        
    }//GEN-LAST:event_no_transaksiMouseClicked

    private void no_transaksiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_transaksiKeyReleased
      
       
        
        
    }//GEN-LAST:event_no_transaksiKeyReleased

    private void no_transaksiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_transaksiKeyTyped
        // TODO add your handling code here:
        
         try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    
    // Buat Statement dengan tipe ResultSet yang mendukung scroll dan concur read-only
    Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
    ResultSet set = st.executeQuery("select * from transaksi where no_transaksi like '%"+no_transaksi.getText()+"%' ");
    
    set.last(); // Pindah ke baris terakhir
    int row = set.getRow(); // Ambil jumlah baris
    int col = set.getMetaData().getColumnCount(); // Ambil jumlah kolom
    set.beforeFirst(); // Kembali ke awal

    String rowData[][] = new String[row][col];
    int r = 0;
    while (set.next()) {
        for (int i = 0; i < col; i++) {
            rowData[r][i] = set.getString(i + 1);
        }
        r++;
    }

    String[] ColumnName = {"NO" ,"No Transaksi", "Kode", "Nama", "Jumlah", "Harga", "Total"};
    DefaultTableModel model = (DefaultTableModel)transakasi_table.getModel();
    model.setDataVector(rowData, ColumnName);

} catch (Exception e) {
    e.printStackTrace();
}
    }//GEN-LAST:event_no_transaksiKeyTyped

    private void transakasi_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transakasi_tableMouseClicked
       
          int id = Integer.parseInt(transakasi_table.getValueAt(transakasi_table.getSelectedRow(),0).toString());
        try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    Statement st = con.createStatement();
    ResultSet res  = st.executeQuery("select * from  transaksi where id="+id);
    while(res.next()){
    nama_barang.setText(res.getString("nama"));
    harga_barang.setText(res.getString("harga"));
    jumlah.setText(res.getString("jumlah"));
    kode_barang.setText(res.getString("kode"));
    
    
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_transakasi_tableMouseClicked

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
         int harga = Integer.parseInt(harga_barang.getText());
     int jumlahnya = Integer.parseInt(this.jumlah.getText());
     int totalnya = harga * jumlahnya;
          int id = Integer.parseInt(transakasi_table.getValueAt(transakasi_table.getSelectedRow(),0).toString());
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cintasehat", "root", "");
    Statement st = con.createStatement();
     String updateStokQuery = "UPDATE obat SET stok = stok + " + jumlahnya + " WHERE kode = '" + kode_barang.getText() + "'";
     int rowsAffected = st.executeUpdate(updateStokQuery);
    int r = JOptionPane.showConfirmDialog(this, "yakin hapus?");
    if(r==0){
    if(!st.execute("delete from transaksi where id="+id) && rowsAffected>0){
        formWindowOpened(null);
    }else{
    JOptionPane.showMessageDialog(this, "batal hapus");
    }
    }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyReleased
        // TODO add your handling code here:
        int bayarnya = Integer.parseInt(bayar.getText());
        int totalnya = Integer.parseInt(totalbayar.getText());
        int kembalianya = totalnya - bayarnya;
        kembalian.setText(String.valueOf(kembalianya));
    }//GEN-LAST:event_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private java.awt.Button button1;
    private javax.swing.JTextField customer;
    private javax.swing.JTextField form_tanggal;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JTextField harga_barang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kode_barang;
    private javax.swing.JTextField nama_barang;
    private javax.swing.JTextField no_transaksi;
    private javax.swing.JButton tambahbtn;
    private javax.swing.JTextField totalbayar;
    private rojerusan.RSTableMetro transakasi_table;
    // End of variables declaration//GEN-END:variables
}
